### PR TITLE
Linux

### PR DESCRIPTION
**Pull request by penberg**
Here's two patches that fix up "rake spec" on my Linux laptop.

### CODE REVIEW

**Comment by naleksi** [comment]
These look good to me. I haven't tested if these work.

**Comment by penberg** [comment]
Thanks. I've only tested these on Linux.

**Comment by arttu** [comment]
@penberg, actually I didn't notice you hadn't committed the Gemfile.lock here before.

Want to re-open this ticket, run `bundle install` and commit-push the .lock file too?

**Comment by arttu** [comment]
@penberg, Unfortunately, your commits and our travis-ci test runner conflicted so I had to remove these commits from upstream.

The build log at http://travis-ci.org/#!/avoinministerio/avoinministerio/builds/762450 advices that the database travis-ci tried to use was sqlite based, since there is a mention about missing constant ActiveRecord::ConnectionAdapters::SQLiteAdapter in the end of the log.

We'll try to figure out what went wrong tomorrow.

**Comment by penberg** [comment]
I fixed both up and will open up a new pull request.

The SQLiteAdapter error was caused by Gemfile.ci explicitly leaving sqlite gem out for postgresql tests.

**Pull request merged**
