### PR TITLE
Only do NewRelic magic if $NEW_RELIC_ID is defined

### PR DESCRIPTION
**Pull request by tmatilai**

### CODE REVIEW

**Comment by ljuti** [comment]
Please move all this to config/environments/production.rb.

**Comment by naleksi** [comment]
Looks good. Let's move to production.rb if it works. I was messing up with the previous staging setup. It was behaving like "ENV=production" but it did not have NewRelic plugin activated. Then I messed up with so many things I cannot even recall anymore if moving out from production.rb to initializer was the thing that actually worked and solved it. But now it can be easily tested. If production.rb works, let's use per ljuti suggestion. tmatilai, would you like to test?

**Comment by tmatilai** [comment]
OK, I'll test with a private Heroku app with and without newrelic addon.

**Comment by tmatilai** [comment]
Does not work. Seems that config/environments/production.rb is called too early and all required instances have not been initialized.

**Comment by ljuti** [comment]
If that's the case, can you add Rails.env.production? condition?

**Comment by tmatilai** [comment]
Sure, but is that really needed? If NEW_RELIC_ID is set and Unicorn and NewRelic gems are installed in in a non-production environment maybe the user really wants to use it?

I'm sorry, but I fail to see the problem that this is causing in non-prod environments...

**Comment by ljuti** [comment]
If the current conditions no longer cause application boot up failures in development and NewRelic is also used in other environments than production, then there's no need to add that.

**Pull request merged**
